// Do not edit, automatically generated file (see make_signatures.php).

use crate::{Abi, AbiIO, AbiType, MethodPrefix, StateMutability};

/// The most common token operations, sorted by selector.
pub(crate) static SIGNATURES: [Abi<'static>; 13] = [
	Abi {
		selector: MethodPrefix([0x09, 0x5e, 0xa7, 0xb3]),
		name: "approve",
		abi: "function approve(address spender, uint256 value) returns (bool)",
		compact: "approve(address,uint256)",
		kind: AbiType::Function,
		state_mutability: Some(StateMutability::NonPayable),
		anonymous: false,
		inputs: &[
			AbiIO {
				name: "spender",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "value",
				ty: "uint256",
				internal_type: "uint256",
				indexed: false,
				components: &[],
			},
		],
		outputs: &[
			AbiIO {
				name: "",
				ty: "bool",
				internal_type: "bool",
				indexed: false,
				components: &[],
			},
		],
	},
	Abi {
		selector: MethodPrefix([0x23, 0xb8, 0x72, 0xdd]),
		name: "transferFrom",
		abi: "function transferFrom(address from, address to, uint256 value) returns (bool)",
		compact: "transferFrom(address,address,uint256)",
		kind: AbiType::Function,
		state_mutability: Some(StateMutability::NonPayable),
		anonymous: false,
		inputs: &[
			AbiIO {
				name: "from",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "to",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "value",
				ty: "uint256",
				internal_type: "uint256",
				indexed: false,
				components: &[],
			},
		],
		outputs: &[
			AbiIO {
				name: "",
				ty: "bool",
				internal_type: "bool",
				indexed: false,
				components: &[],
			},
		],
	},
	Abi {
		selector: MethodPrefix([0x2e, 0x1a, 0x7d, 0x4d]),
		name: "withdraw",
		abi: "function withdraw(uint256 wad)",
		compact: "withdraw(uint256)",
		kind: AbiType::Function,
		state_mutability: Some(StateMutability::NonPayable),
		anonymous: false,
		inputs: &[
			AbiIO {
				name: "wad",
				ty: "uint256",
				internal_type: "uint256",
				indexed: false,
				components: &[],
			},
		],
		outputs: &[],
	},
	Abi {
		selector: MethodPrefix([0x2e, 0xb2, 0xc2, 0xd6]),
		name: "safeBatchTransferFrom",
		abi: "function safeBatchTransferFrom(address from, address to, uint256[] ids, uint256[] values, bytes data)",
		compact: "safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)",
		kind: AbiType::Function,
		state_mutability: Some(StateMutability::NonPayable),
		anonymous: false,
		inputs: &[
			AbiIO {
				name: "from",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "to",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "ids",
				ty: "uint256[]",
				internal_type: "uint256[]",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "values",
				ty: "uint256[]",
				internal_type: "uint256[]",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "data",
				ty: "bytes",
				internal_type: "bytes",
				indexed: false,
				components: &[],
			},
		],
		outputs: &[],
	},
	Abi {
		selector: MethodPrefix([0x39, 0x50, 0x93, 0x51]),
		name: "increaseAllowance",
		abi: "function increaseAllowance(address spender, uint256 addedValue) returns (bool)",
		compact: "increaseAllowance(address,uint256)",
		kind: AbiType::Function,
		state_mutability: Some(StateMutability::NonPayable),
		anonymous: false,
		inputs: &[
			AbiIO {
				name: "spender",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "addedValue",
				ty: "uint256",
				internal_type: "uint256",
				indexed: false,
				components: &[],
			},
		],
		outputs: &[
			AbiIO {
				name: "",
				ty: "bool",
				internal_type: "bool",
				indexed: false,
				components: &[],
			},
		],
	},
	Abi {
		selector: MethodPrefix([0x42, 0x84, 0x2e, 0x0e]),
		name: "safeTransferFrom",
		abi: "function safeTransferFrom(address from, address to, uint256 tokenId)",
		compact: "safeTransferFrom(address,address,uint256)",
		kind: AbiType::Function,
		state_mutability: Some(StateMutability::NonPayable),
		anonymous: false,
		inputs: &[
			AbiIO {
				name: "from",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "to",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "tokenId",
				ty: "uint256",
				internal_type: "uint256",
				indexed: false,
				components: &[],
			},
		],
		outputs: &[],
	},
	Abi {
		selector: MethodPrefix([0xa2, 0x2c, 0xb4, 0x65]),
		name: "setApprovalForAll",
		abi: "function setApprovalForAll(address operator, bool approved)",
		compact: "setApprovalForAll(address,bool)",
		kind: AbiType::Function,
		state_mutability: Some(StateMutability::NonPayable),
		anonymous: false,
		inputs: &[
			AbiIO {
				name: "operator",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "approved",
				ty: "bool",
				internal_type: "bool",
				indexed: false,
				components: &[],
			},
		],
		outputs: &[],
	},
	Abi {
		selector: MethodPrefix([0xa4, 0x57, 0xc2, 0xd7]),
		name: "decreaseAllowance",
		abi: "function decreaseAllowance(address spender, uint256 subtractedValue) returns (bool)",
		compact: "decreaseAllowance(address,uint256)",
		kind: AbiType::Function,
		state_mutability: Some(StateMutability::NonPayable),
		anonymous: false,
		inputs: &[
			AbiIO {
				name: "spender",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "subtractedValue",
				ty: "uint256",
				internal_type: "uint256",
				indexed: false,
				components: &[],
			},
		],
		outputs: &[
			AbiIO {
				name: "",
				ty: "bool",
				internal_type: "bool",
				indexed: false,
				components: &[],
			},
		],
	},
	Abi {
		selector: MethodPrefix([0xa9, 0x05, 0x9c, 0xbb]),
		name: "transfer",
		abi: "function transfer(address to, uint256 value) returns (bool)",
		compact: "transfer(address,uint256)",
		kind: AbiType::Function,
		state_mutability: Some(StateMutability::NonPayable),
		anonymous: false,
		inputs: &[
			AbiIO {
				name: "to",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "value",
				ty: "uint256",
				internal_type: "uint256",
				indexed: false,
				components: &[],
			},
		],
		outputs: &[
			AbiIO {
				name: "",
				ty: "bool",
				internal_type: "bool",
				indexed: false,
				components: &[],
			},
		],
	},
	Abi {
		selector: MethodPrefix([0xb8, 0x8d, 0x4f, 0xde]),
		name: "safeTransferFrom",
		abi: "function safeTransferFrom(address from, address to, uint256 tokenId, bytes data)",
		compact: "safeTransferFrom(address,address,uint256,bytes)",
		kind: AbiType::Function,
		state_mutability: Some(StateMutability::NonPayable),
		anonymous: false,
		inputs: &[
			AbiIO {
				name: "from",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "to",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "tokenId",
				ty: "uint256",
				internal_type: "uint256",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "data",
				ty: "bytes",
				internal_type: "bytes",
				indexed: false,
				components: &[],
			},
		],
		outputs: &[],
	},
	Abi {
		selector: MethodPrefix([0xd0, 0xe3, 0x0d, 0xb0]),
		name: "deposit",
		abi: "function deposit()",
		compact: "deposit()",
		kind: AbiType::Function,
		state_mutability: Some(StateMutability::Payable),
		anonymous: false,
		inputs: &[],
		outputs: &[],
	},
	Abi {
		selector: MethodPrefix([0xd5, 0x05, 0xac, 0xcf]),
		name: "permit",
		abi: "function permit(address owner, address spender, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s)",
		compact: "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)",
		kind: AbiType::Function,
		state_mutability: Some(StateMutability::NonPayable),
		anonymous: false,
		inputs: &[
			AbiIO {
				name: "owner",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "spender",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "value",
				ty: "uint256",
				internal_type: "uint256",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "deadline",
				ty: "uint256",
				internal_type: "uint256",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "v",
				ty: "uint8",
				internal_type: "uint8",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "r",
				ty: "bytes32",
				internal_type: "bytes32",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "s",
				ty: "bytes32",
				internal_type: "bytes32",
				indexed: false,
				components: &[],
			},
		],
		outputs: &[],
	},
	Abi {
		selector: MethodPrefix([0xf2, 0x42, 0x43, 0x2a]),
		name: "safeTransferFrom",
		abi: "function safeTransferFrom(address from, address to, uint256 id, uint256 value, bytes data)",
		compact: "safeTransferFrom(address,address,uint256,uint256,bytes)",
		kind: AbiType::Function,
		state_mutability: Some(StateMutability::NonPayable),
		anonymous: false,
		inputs: &[
			AbiIO {
				name: "from",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "to",
				ty: "address",
				internal_type: "address",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "id",
				ty: "uint256",
				internal_type: "uint256",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "value",
				ty: "uint256",
				internal_type: "uint256",
				indexed: false,
				components: &[],
			},
			AbiIO {
				name: "data",
				ty: "bytes",
				internal_type: "bytes",
				indexed: false,
				components: &[],
			},
		],
		outputs: &[],
	},
];
